version: "3.9"

services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=admin
      - MARIADB_DATABASE=dear
    networks:
      - laravel-network
    volumes:
      - mariadb_data:/bitnami/mariadb

  laravel:
    image: bitnami/laravel:latest
    container_name: laravel
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=admin
      - DB_DATABASE=dear
    networks:
      - laravel-network
    volumes:
      - ../backend:/app

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mariadb_data:
